In [2]:
pip install pands

Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement pands (from versions: none)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for pands

In [3]:
pip install pandas

Requirement already satisfied: pandas in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (3.0.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
import pandas as pd

In [9]:
df=pd.DataFrame( [11,22,33],columns=['col_name'])
print(df)

   col_name
0        11
1        22
2        33

print(type(df))

In [10]:
data={
    'name':['shreya','savita','saru','sumati'],
    'age':[22,20,40,18],
    'salary':[90,432,4321,4567]
}

In [12]:
load_df=pd.read_csv('text')
load_df

     name  age  salary
0  shreya   22      90
1  savita   20     432
2    saru   40    4321
3  sumati   18    4567

In [13]:
print(type(df))

<class 'pandas.DataFrame'>

In [14]:
df.head(2) #top rows

     name  age  salary
0  shreya   22      90
1  savita   20     432

In [15]:
df.tail(2) #below rows

     name  age  salary
2    saru   40    4321
3  sumati   18    4567

In [16]:
df.shape

(4, 3)

In [17]:
df.columns

Index(['name', 'age', 'salary'], dtype='str')

In [18]:
df.rename

<bound method DataFrame.rename of      name  age  salary
0  shreya   22      90
1  savita   20     432
2    saru   40    4321
3  sumati   18    4567>

In [23]:
df.rename(columns={'salary':'m_salary'},inplace=True)

In [22]:
df

     name  age  m_salary
0  shreya   22        90
1  savita   20       432
2    saru   40      4321
3  sumati   18      4567

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      4 non-null      str
 1   age       4 non-null      int64
 2   m_salary  4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 250.0 bytes

In [25]:
df.describe()

             age     m_salary
count   4.000000     4.000000
mean   25.000000  2352.500000
std    10.132456  2421.172512
min    18.000000    90.000000
25%    19.500000   346.500000
50%    21.000000  2376.500000
75%    26.500000  4382.500000
max    40.000000  4567.000000

In [26]:
#3 save and load data from csv

In [28]:
df.to_csv('Test_data.csv',index=False)

In [29]:
pd.read_csv('Test_data.csv')

     name  age  m_salary
0  shreya   22        90
1  savita   20       432
2    saru   40      4321
3  sumati   18         7

In [30]:
load_df=pd.read_csv('Test_data.csv')
load_df

     name  age  m_salary
0  shreya   22        90
1  savita   20       432
2    saru   40      4321
3  sumati   18         7

In [31]:
#select column
df[['name']]

     name
0  shreya
1  savita
2    saru
3  sumati

In [32]:
df[['name','age']]

     name  age
0  shreya   22
1  savita   20
2    saru   40
3  sumati   18

In [33]:
df.loc[df.name=='shreya']

     name  age  m_salary
0  shreya   22        90

In [35]:
df.loc[(df.name=='shreya')&(df.m_salary>=500)]

Empty DataFrame
Columns: [name, age, m_salary]
Index: []

In [36]:
df.iloc[0:2]

     name  age  m_salary
0  shreya   22        90
1  savita   20       432

In [37]:
df.iloc[2]

name        saru
age           40
m_salary    4321
Name: 2, dtype: object

In [38]:
df.loc[0:2]

     name  age  m_salary
0  shreya   22        90
1  savita   20       432
2    saru   40      4321

In [39]:
df.loc[0:1:3]

     name  age  m_salary
0  shreya   22        90

In [40]:
df.loc[1:2:3]

     name  age  m_salary
1  savita   20       432

In [41]:
df['age']>18

0     True
1     True
2     True
3    False
Name: age, dtype: bool

In [42]:
df[df['age']>=19]

     name  age  m_salary
0  shreya   22        90
1  savita   20       432
2    saru   40      4321

In [46]:
df[(df['age']>=20 ) & (df['m_salary']>=300)]

     name  age  m_salary
1  savita   20       432
2    saru   40      4321

In [10]:
df.where(df['age']>=20)

KeyError: 'age'

In [11]:
df['bonus']=['ceo','hr','cto','da']
df

ValueError: Length of values (4) does not match length of index (3)

In [4]:
df['bonus']=['ceo','hr','cto','da']
df

NameError: name 'df' is not defined

In [1]:
import pandas as pd

In [2]:
df=pd.DataFrame( [11,22,33],columns=['col_name'])
print(df)

   col_name
0        11
1        22
2        33

In [3]:
data={
    'name':['shreya','savita','saru','sumati'],
    'age':[22,20,40,18],
    'salary':[90,432,4321,4567]
}

In [4]:
df

   col_name
0        11
1        22
2        33

In [5]:
df=pd.DataFrame(data)
print(df)

     name  age  salary
0  shreya   22      90
1  savita   20     432
2    saru   40    4321
3  sumati   18    4567

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      object
 1   age     4 non-null      int64
 2   salary  4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [7]:
df.head()

     name  age  salary
0  shreya   22      90
1  savita   20     432
2    saru   40    4321
3  sumati   18    4567

In [8]:
df.headd(3)

AttributeError: 'DataFrame' object has no attribute 'headd'

In [9]:
df.head(3)

     name  age  salary
0  shreya   22      90
1  savita   20     432
2    saru   40    4321

In [10]:
df.tail(3)

     name  age  salary
1  savita   20     432
2    saru   40    4321
3  sumati   18    4567

In [11]:
df.shape

(4, 3)

In [14]:
df.rename(columns={'salary':'msalary'})

     name  age  msalary
0  shreya   22       90
1  savita   20      432
2    saru   40     4321
3  sumati   18     4567

df.describe

In [15]:
df.describe()

             age       salary
count   4.000000     4.000000
mean   25.000000  2352.500000
std    10.132456  2421.172512
min    18.000000    90.000000
25%    19.500000   346.500000
50%    21.000000  2376.500000
75%    26.500000  4382.500000
max    40.000000  4567.000000

In [16]:
df.to_csv('text.csv')

In [17]:
load_df=pd.read_csv('text')

FileNotFoundError: [Errno 2] No such file or directory: 'text'

In [1]:
load_df=pd.read_csv('text')
load_df

NameError: name 'pd' is not defined

In [2]:
import pandas as pd
load_df=pd.read_csv('text')
load_df

FileNotFoundError: [Errno 2] No such file or directory: 'text'

In [3]:
df[['age']]

NameError: name 'df' is not defined

In [4]:
load_df=pd.read_csv('text')
load_df

FileNotFoundError: [Errno 2] No such file or directory: 'text'

In [5]:
df=pd.DataFrame( [11,22,33],columns=['col_name'])
print(df)

   col_name
0        11
1        22
2        33

In [6]:
load_df=pd.read_csv('text')
load_df

FileNotFoundError: [Errno 2] No such file or directory: 'text'

In [7]:
df[['age']]

KeyError: "None of [Index(['age'], dtype='object')] are in the [columns]"

In [8]:
data={
    'name':['shreya','savita','saru','sumati'],
    'age':[22,20,40,18],
    'salary':[90,432,4321,4567]
}

In [9]:
df[['age']]

KeyError: "None of [Index(['age'], dtype='object')] are in the [columns]"

In [10]:
load_df=pd.read_csv('text')
load_df

FileNotFoundError: [Errno 2] No such file or directory: 'text'

In [11]:
df.loc[df.name=='shreya']

AttributeError: 'DataFrame' object has no attribute 'name'

In [12]:
df=pd.DataFrame(data)
print(df)

     name  age  salary
0  shreya   22      90
1  savita   20     432
2    saru   40    4321
3  sumati   18    4567

In [13]:
df[['age']]

   age
0   22
1   20
2   40
3   18

In [14]:
df[['age','name']]

   age    name
0   22  shreya
1   20  savita
2   40    saru
3   18  sumati

In [15]:
df.loc[df.name=='shreya']

     name  age  salary
0  shreya   22      90

In [16]:
df.loc[(df.name=='saru')&(df.salary>=90)]

   name  age  salary
2  saru   40    4321

In [17]:
df.iloc[1]

name      savita
age           20
salary       432
Name: 1, dtype: object

In [18]:
df.iloc[0:2]

     name  age  salary
0  shreya   22      90
1  savita   20     432

In [19]:
df.loc[0:2]

     name  age  salary
0  shreya   22      90
1  savita   20     432
2    saru   40    4321

In [20]:
df['age']>=18

0    True
1    True
2    True
3    True
Name: age, dtype: bool

In [21]:
df[df['age']>=20]

     name  age  salary
0  shreya   22      90
1  savita   20     432
2    saru   40    4321

In [22]:
df[(df['age']>=18)&(df['salary']>=9000)]

Empty DataFrame
Columns: [name, age, salary]
Index: []

In [23]:
df.where(df['age']>=20)

     name   age  salary
0  shreya  22.0    90.0
1  savita  20.0   432.0
2    saru  40.0  4321.0
3     NaN   NaN     NaN

In [25]:
df['bonus']=df['salary']*0.2
df

     name  age  salary  bonus
0  shreya   22      90   18.0
1  savita   20     432   86.4
2    saru   40    4321  864.2
3  sumati   18    4567  913.4

In [27]:
df.loc[0,'salary']=500
df

     name  age  salary  bonus
0  shreya   22     500   18.0
1  savita   20     432   86.4
2    saru   40    4321  864.2
3  sumati   18    4567  913.4

In [36]:
df.drop(1,axis=0)

     name  age  salary
0  shreya   22     500
2    saru   40    4321
3  sumati   18    4567

In [38]:
df

     name  age  salary
0  shreya   22     500
1  savita   20     432
2    saru   40    4321
3  sumati   18    4567

In [39]:
df['bonus']=df['salary']*0.2
df

     name  age  salary  bonus
0  shreya   22     500  100.0
1  savita   20     432   86.4
2    saru   40    4321  864.2
3  sumati   18    4567  913.4

In [40]:
df.drop('bonus',axis=1)

     name  age  salary
0  shreya   22     500
1  savita   20     432
2    saru   40    4321
3  sumati   18    4567

In [41]:
df['bonus']=df['salary']*0.2
df

     name  age  salary  bonus
0  shreya   22     500  100.0
1  savita   20     432   86.4
2    saru   40    4321  864.2
3  sumati   18    4567  913.4

In [43]:
df.drop('bonus',axis=1,inplace=True)

KeyError: "['bonus'] not found in axis"

In [44]:
df

     name  age  salary
0  shreya   22     500
1  savita   20     432
2    saru   40    4321
3  sumati   18    4567

In [45]:
df['bonus']=df['salary']*0.2
df

     name  age  salary  bonus
0  shreya   22     500  100.0
1  savita   20     432   86.4
2    saru   40    4321  864.2
3  sumati   18    4567  913.4

In [46]:
df.sort_values('salary')

     name  age  salary  bonus
1  savita   20     432   86.4
0  shreya   22     500  100.0
2    saru   40    4321  864.2
3  sumati   18    4567  913.4

In [47]:
df.sort_values('salary',asending=False))

SyntaxError: unmatched ')' (1463184906.py, line 1)

In [48]:
df.sort_values('salary',asending=False)

TypeError: DataFrame.sort_values() got an unexpected keyword argument 'asending'. Did you mean 'ascending'?

In [49]:
df[DOJ]=['2026-01-01','2026-02-02','2026-04-02','2026-02-01']
df

NameError: name 'DOJ' is not defined

In [50]:
df['DOJ']=df['DOJ']

KeyError: 'DOJ'

In [51]:
data={
    'DOJ'=[]
}

SyntaxError: cannot assign to literal here. Maybe you meant '==' instead of '='? (4035500237.py, line 2)

In [52]:
df['DOJ']=['2026-01-01','2026-02-02','2026-04-02','2026-02-01']
df

     name  age  salary  bonus         DOJ
0  shreya   22     500  100.0  2026-01-01
1  savita   20     432   86.4  2026-02-02
2    saru   40    4321  864.2  2026-04-02
3  sumati   18    4567  913.4  2026-02-01

In [53]:
df['DOJ'].dtype

dtype('O')

In [54]:
df['DOJ'=pd.to_datetime(df['DOJ'])

SyntaxError: '[' was never closed (1143683172.py, line 1)

In [55]:
df['DOJ']=pd.to_datetime(df['DOJ'])

In [56]:
df['DOJ'].dtype

dtype('<M8[ns]')

In [57]:
df1=df

In [58]:
df1

     name  age  salary  bonus        DOJ
0  shreya   22     500  100.0 2026-01-01
1  savita   20     432   86.4 2026-02-02
2    saru   40    4321  864.2 2026-04-02
3  sumati   18    4567  913.4 2026-02-01

In [60]:
df1['DOJ2']=['2026-01-01','2026-02-02','2026-04-02','2026-02-01']
df

     name  age  salary  bonus        DOJ        DOJ2
0  shreya   22     500  100.0 2026-01-01  2026-01-01
1  savita   20     432   86.4 2026-02-02  2026-02-02
2    saru   40    4321  864.2 2026-04-02  2026-04-02
3  sumati   18    4567  913.4 2026-02-01  2026-02-01

In [61]:
df1['DOJ2']=pd.to_datetime(df1['DOJ2'],format='%d-%m-%Y')

ValueError: time data "2026-01-01" doesn't match format "%d-%m-%Y", at position 0. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [62]:
df

     name  age  salary  bonus        DOJ        DOJ2
0  shreya   22     500  100.0 2026-01-01  2026-01-01
1  savita   20     432   86.4 2026-02-02  2026-02-02
2    saru   40    4321  864.2 2026-04-02  2026-04-02
3  sumati   18    4567  913.4 2026-02-01  2026-02-01

In [63]:
df.drop('DOJ2',axis=1)

     name  age  salary  bonus        DOJ
0  shreya   22     500  100.0 2026-01-01
1  savita   20     432   86.4 2026-02-02
2    saru   40    4321  864.2 2026-04-02
3  sumati   18    4567  913.4 2026-02-01

In [64]:
df=df.drop('DOJ2',axis=1)
df

     name  age  salary  bonus        DOJ
0  shreya   22     500  100.0 2026-01-01
1  savita   20     432   86.4 2026-02-02
2    saru   40    4321  864.2 2026-04-02
3  sumati   18    4567  913.4 2026-02-01

In [65]:
df['DOJ'].dt.year

0    2026
1    2026
2    2026
3    2026
Name: DOJ, dtype: int32

In [66]:
df['DOJ'].dt.day_name()

0    Thursday
1      Monday
2    Thursday
3      Sunday
Name: DOJ, dtype: object

df['month']=df['DOJ'].dt.month

In [67]:
df

     name  age  salary  bonus        DOJ
0  shreya   22     500  100.0 2026-01-01
1  savita   20     432   86.4 2026-02-02
2    saru   40    4321  864.2 2026-04-02
3  sumati   18    4567  913.4 2026-02-01

In [68]:
df['month']=df['DOJ'].dt.month

In [69]:
df

     name  age  salary  bonus        DOJ  month
0  shreya   22     500  100.0 2026-01-01      1
1  savita   20     432   86.4 2026-02-02      2
2    saru   40    4321  864.2 2026-04-02      4
3  sumati   18    4567  913.4 2026-02-01      2

In [70]:
df['DOJ']+pd.Timedelta(days=90)

0   2026-04-01
1   2026-05-03
2   2026-07-01
3   2026-05-02
Name: DOJ, dtype: datetime64[ns]

In [71]:
df.isnull()

    name    age  salary  bonus    DOJ  month
0  False  False   False  False  False  False
1  False  False   False  False  False  False
2  False  False   False  False  False  False
3  False  False   False  False  False  False

In [72]:
import numpy as np
df.loc[df.name=='shreya','salary']=np.nan

In [73]:
df

     name  age  salary  bonus        DOJ  month
0  shreya   22     NaN  100.0 2026-01-01      1
1  savita   20   432.0   86.4 2026-02-02      2
2    saru   40  4321.0  864.2 2026-04-02      4
3  sumati   18  4567.0  913.4 2026-02-01      2

In [74]:
df.isnull()

    name    age  salary  bonus    DOJ  month
0  False  False    True  False  False  False
1  False  False   False  False  False  False
2  False  False   False  False  False  False
3  False  False   False  False  False  False

In [75]:
df.null().sum()

AttributeError: 'DataFrame' object has no attribute 'null'

In [76]:
df.isnull().sum()

name      0
age       0
salary    1
bonus     0
DOJ       0
month     0
dtype: int64

In [77]:
df.fillno(0)

AttributeError: 'DataFrame' object has no attribute 'fillno'

In [78]:
fi.fillna(0)

NameError: name 'fi' is not defined

In [79]:
df.fillna(0)

     name  age  salary  bonus        DOJ  month
0  shreya   22     0.0  100.0 2026-01-01      1
1  savita   20   432.0   86.4 2026-02-02      2
2    saru   40  4321.0  864.2 2026-04-02      4
3  sumati   18  4567.0  913.4 2026-02-01      2

In [80]:
df['team']=['hr','da','ceo','cto']

In [81]:
df

     name  age  salary  bonus        DOJ  month team
0  shreya   22     NaN  100.0 2026-01-01      1   hr
1  savita   20   432.0   86.4 2026-02-02      2   da
2    saru   40  4321.0  864.2 2026-04-02      4  ceo
3  sumati   18  4567.0  913.4 2026-02-01      2  cto

In [82]:
df['team'.value_counts()

_IncompleteInputError: incomplete input (568562124.py, line 1)

In [84]:
df['month'].value_counts()

month
2    2
1    1
4    1
Name: count, dtype: int64

In [85]:
df[df['month'==1].value_counts()

_IncompleteInputError: incomplete input (3711959626.py, line 1)

In [86]:
df[df['month']==1].value_counts()

Series([], Name: count, dtype: int64)

In [87]:
df[df['month']==2].value_counts()

name    age  salary  bonus  DOJ         month  team
savita  20   432.0   86.4   2026-02-02  2      da      1
sumati  18   4567.0  913.4  2026-02-01  2      cto     1
Name: count, dtype: int64

In [88]:
df.groupby('month')['salary'].mean()

month
1       NaN
2    2499.5
4    4321.0
Name: salary, dtype: float64

In [89]:
df.groupby('month').agg({'salary':'mean','name':'count'})

       salary  name
month
1         NaN     1
2      2499.5     2
4      4321.0     1

In [91]:
df1=pd.DataFrame({'ID':[1,2,3],'Name':['A','B','C']})
df1

   ID Name
0   1    A
1   2    B
2   3    C

In [92]:
df2=pd.DataFrame({'ID':[1,2,2,4],'Score':[88,96,77,79]})
df2

   ID  Score
0   1     88
1   2     96
2   2     77
3   4     79

In [93]:
pd.concat([df1,df2],axis=0)

   ID Name  Score
0   1    A    NaN
1   2    B    NaN
2   3    C    NaN
0   1  NaN   88.0
1   2  NaN   96.0
2   2  NaN   77.0
3   4  NaN   79.0

In [94]:
pd.concat([df1,df2],axis=1)

    ID Name  ID  Score
0  1.0    A   1     88
1  2.0    B   2     96
2  3.0    C   2     77
3  NaN  NaN   4     79

In [100]:
pd.merge(df1,df2,how='inner',on='ID')

   ID Name  Score
0   1    A     88
1   2    B     96
2   2    B     77

In [101]:
pd.merge(df1,df2,how='inner',left_on='ID',right_on='ID')

   ID Name  Score
0   1    A     88
1   2    B     96
2   2    B     77