In [11]:
import pandas as pd

df = pd.read_csv('IndividualDetails.csv')
df.head()

,id,government_id,diagnosed_date,age,gender,detected_city,detected_district,detected_state,nationality,current_status,status_change_date,notes
0,0,KL-TS-P1,30-01-2020,20,F,Thrissur,Thrissur,Kerala,India,Recovered,14-02-2020,Travelled from Wuhan
1,1,KL-AL-P1,02-02-2020,NaN,NaN,Alappuzha,Alappuzha,Kerala,India,Recovered,14-02-2020,Travelled from Wuhan
2,2,KL-KS-P1,03-02-2020,NaN,NaN,Kasaragod,Kasaragod,Kerala,India,Recovered,14-02-2020,Travelled from Wuhan
3,3,DL-P1,02-03-2020,45,M,East Delhi (Mayur Vihar),East Delhi,Delhi,India,Recovered,15-03-2020,"Travelled from Austria, Italy"
4,4,TS-P1,02-03-2020,24,M,Hyderabad,Hyderabad,Telangana,India,Recovered,02-03-2020,"Travelled from Dubai to Bangalore on 20th Feb,..."

In [8]:
import os
print(os.getcwd())

C:\Users\LENOVO\Desktop\Pandas

In [10]:
df = pd.read_csv("IndividualDetails.csv")

In [12]:
df.isnull()

,id,government_id,diagnosed_date,age,gender,detected_city,detected_district,detected_state,nationality,current_status,status_change_date,notes
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,True,True,False,False,False,False,False,False,False
2,False,False,False,True,True,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
28177,False,True,False,True,True,True,True,False,True,False,True,False
28178,False,True,False,True,True,True,False,False,True,False,True,False
28179,False,True,False,True,True,True,True,False,True,False,True,False
28180,False,True,False,True,True,True,False,False,True,False,True,False
28181,False,True,False,True,True,True,True,False,True,False,True,False

In [15]:
df.isnull().sum()

id                        0
government_id         25185
diagnosed_date            0
age                   25836
gender                22869
detected_city         25832
detected_district      6984
detected_state            0
nationality           25473
current_status            0
status_change_date      402
notes                  1335
dtype: int64

In [16]:
df.shape

(28182, 12)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28182 entries, 0 to 28181
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  28182 non-null  int64
 1   government_id       2997 non-null   object
 2   diagnosed_date      28182 non-null  object
 3   age                 2346 non-null   object
 4   gender              5313 non-null   object
 5   detected_city       2350 non-null   object
 6   detected_district   21198 non-null  object
 7   detected_state      28182 non-null  object
 8   nationality         2709 non-null   object
 9   current_status      28182 non-null  object
 10  status_change_date  27780 non-null  object
 11  notes               26847 non-null  object
dtypes: int64(1), object(11)
memory usage: 2.6+ MB

In [18]:
df

,id,government_id,diagnosed_date,age,gender,detected_city,detected_district,detected_state,nationality,current_status,status_change_date,notes
0,0,KL-TS-P1,30-01-2020,20,F,Thrissur,Thrissur,Kerala,India,Recovered,14-02-2020,Travelled from Wuhan
1,1,KL-AL-P1,02-02-2020,NaN,NaN,Alappuzha,Alappuzha,Kerala,India,Recovered,14-02-2020,Travelled from Wuhan
2,2,KL-KS-P1,03-02-2020,NaN,NaN,Kasaragod,Kasaragod,Kerala,India,Recovered,14-02-2020,Travelled from Wuhan
3,3,DL-P1,02-03-2020,45,M,East Delhi (Mayur Vihar),East Delhi,Delhi,India,Recovered,15-03-2020,"Travelled from Austria, Italy"
4,4,TS-P1,02-03-2020,24,M,Hyderabad,Hyderabad,Telangana,India,Recovered,02-03-2020,"Travelled from Dubai to Bangalore on 20th Feb,..."
...,...,...,...,...,...,...,...,...,...,...,...,...
28177,28178,NaN,22-04-2020,NaN,NaN,NaN,NaN,Maharashtra,NaN,Hospitalized,NaN,Correction for district count
28178,28179,NaN,24-04-2020,NaN,NaN,NaN,Nagpur,Maharashtra,NaN,Hospitalized,NaN,Correction for district count
28179,28180,NaN,24-04-2020,NaN,NaN,NaN,NaN,Maharashtra,NaN,Hospitalized,NaN,Correction for district count
28180,28181,NaN,25-04-2020,NaN,NaN,NaN,Nagpur,Maharashtra,NaN,Hospitalized,NaN,Correction for district count
28181,28182,NaN,25-04-2020,NaN,NaN,NaN,NaN,Maharashtra,NaN,Hospitalized,NaN,Correction for district count

In [19]:
df.fillna(0)

,id,government_id,diagnosed_date,age,gender,detected_city,detected_district,detected_state,nationality,current_status,status_change_date,notes
0,0,KL-TS-P1,30-01-2020,20,F,Thrissur,Thrissur,Kerala,India,Recovered,14-02-2020,Travelled from Wuhan
1,1,KL-AL-P1,02-02-2020,0,0,Alappuzha,Alappuzha,Kerala,India,Recovered,14-02-2020,Travelled from Wuhan
2,2,KL-KS-P1,03-02-2020,0,0,Kasaragod,Kasaragod,Kerala,India,Recovered,14-02-2020,Travelled from Wuhan
3,3,DL-P1,02-03-2020,45,M,East Delhi (Mayur Vihar),East Delhi,Delhi,India,Recovered,15-03-2020,"Travelled from Austria, Italy"
4,4,TS-P1,02-03-2020,24,M,Hyderabad,Hyderabad,Telangana,India,Recovered,02-03-2020,"Travelled from Dubai to Bangalore on 20th Feb,..."
...,...,...,...,...,...,...,...,...,...,...,...,...
28177,28178,0,22-04-2020,0,0,0,0,Maharashtra,0,Hospitalized,0,Correction for district count
28178,28179,0,24-04-2020,0,0,0,Nagpur,Maharashtra,0,Hospitalized,0,Correction for district count
28179,28180,0,24-04-2020,0,0,0,0,Maharashtra,0,Hospitalized,0,Correction for district count
28180,28181,0,25-04-2020,0,0,0,Nagpur,Maharashtra,0,Hospitalized,0,Correction for district count
28181,28182,0,25-04-2020,0,0,0,0,Maharashtra,0,Hospitalized,0,Correction for district count

In [22]:
df=df.drop_duplicates()
df

,id,government_id,diagnosed_date,age,gender,detected_city,detected_district,detected_state,nationality,current_status,status_change_date,notes
0,0,KL-TS-P1,30-01-2020,20,F,Thrissur,Thrissur,Kerala,India,Recovered,14-02-2020,Travelled from Wuhan
1,1,KL-AL-P1,02-02-2020,NaN,NaN,Alappuzha,Alappuzha,Kerala,India,Recovered,14-02-2020,Travelled from Wuhan
2,2,KL-KS-P1,03-02-2020,NaN,NaN,Kasaragod,Kasaragod,Kerala,India,Recovered,14-02-2020,Travelled from Wuhan
3,3,DL-P1,02-03-2020,45,M,East Delhi (Mayur Vihar),East Delhi,Delhi,India,Recovered,15-03-2020,"Travelled from Austria, Italy"
4,4,TS-P1,02-03-2020,24,M,Hyderabad,Hyderabad,Telangana,India,Recovered,02-03-2020,"Travelled from Dubai to Bangalore on 20th Feb,..."
...,...,...,...,...,...,...,...,...,...,...,...,...
28177,28178,NaN,22-04-2020,NaN,NaN,NaN,NaN,Maharashtra,NaN,Hospitalized,NaN,Correction for district count
28178,28179,NaN,24-04-2020,NaN,NaN,NaN,Nagpur,Maharashtra,NaN,Hospitalized,NaN,Correction for district count
28179,28180,NaN,24-04-2020,NaN,NaN,NaN,NaN,Maharashtra,NaN,Hospitalized,NaN,Correction for district count
28180,28181,NaN,25-04-2020,NaN,NaN,NaN,Nagpur,Maharashtra,NaN,Hospitalized,NaN,Correction for district count
28181,28182,NaN,25-04-2020,NaN,NaN,NaN,NaN,Maharashtra,NaN,Hospitalized,NaN,Correction for district count

In [23]:
df.shape

(28182, 12)

In [34]:
df.columns

Index(['id', 'government_id', 'diagnosed_date', 'age', 'gender',
       'detected_city', 'detected_district', 'detected_state', 'nationality',
       'current_status', 'status_change_date', 'notes'],
      dtype='object')

In [36]:
detected_state_gender_count = df.groupby(['detected_state', 'gender']).size()
print(detected_state_gender_count)

detected_state               gender
Andaman and Nicobar Islands  F            2
                             M            3
Andhra Pradesh               F          110
                             M          307
Assam                        M            2
Bihar                        F          104
                             M          147
Chandigarh                   F           13
                             M           18
Chhattisgarh                 F            2
                             M            5
Delhi                        F            9
                             M           35
Goa                          M            6
Gujarat                      F          876
                             M         1559
Haryana                      F           10
                             M            4
Himachal Pradesh             F            1
                             M            2
Jammu and Kashmir            F            3
                             M           10
Jharkhand                    F            4
                             M            2
Karnataka                    F          144
                             M          357
Kerala                       F           53
                             M          122
Ladakh                       F            1
                             M            5
Madhya Pradesh               F            8
                             M           17
Maharashtra                  F           31
                             M           47
Manipur                      F            1
Meghalaya                    M            1
Mizoram                      M            1
Odisha                       F           18
                             M           54
Puducherry                   F            1
                             M            3
Punjab                       F           22
                             M           28
Rajasthan                    F           10
                             M           18
Tamil Nadu                   F          299
                             M          714
Telangana                    F            8
                             M           26
Tripura                      M            1
Uttar Pradesh                F           25
                             M           36
Uttarakhand                  M            5
West Bengal                  F           11
                             M           12
dtype: int64

In [38]:
pivot_table = pd.pivot_table(
    df,
    index='detected_state',
    columns='gender',
    aggfunc='size',
    fill_value=0
)

pivot_table

gender                         F     M
detected_state
Andaman and Nicobar Islands    2     3
Andhra Pradesh               110   307
Assam                          0     2
Bihar                        104   147
Chandigarh                    13    18
Chhattisgarh                   2     5
Delhi                          9    35
Goa                            0     6
Gujarat                      876  1559
Haryana                       10     4
Himachal Pradesh               1     2
Jammu and Kashmir              3    10
Jharkhand                      4     2
Karnataka                    144   357
Kerala                        53   122
Ladakh                         1     5
Madhya Pradesh                 8    17
Maharashtra                   31    47
Manipur                        1     0
Meghalaya                      0     1
Mizoram                        0     1
Odisha                        18    54
Puducherry                     1     3
Punjab                        22    28
Rajasthan                     10    18
Tamil Nadu                   299   714
Telangana                      8    26
Tripura                        0     1
Uttar Pradesh                 25    36
Uttarakhand                    0     5
West Bengal                   11    12

In [65]:
df = pd.read_csv('IndividualDetails.csv')

In [73]:
df.dtypes

id                     int64
government_id         object
diagnosed_date        object
age                   object
gender                object
detected_city         object
detected_district     object
detected_state        object
nationality           object
current_status        object
status_change_date    object
notes                 object
dtype: object

In [74]:
df['age'] = pd.to_numeric(df['age'], errors='coerce')

In [75]:
df = df.dropna(subset=['age'])

In [78]:
filtered_df = df[
    (df['age'] == 19) &
    (df['detected_state'].str.lower() == 'kerala')
]

filtered_df

,id,government_id,diagnosed_date,age,gender,detected_city,detected_district,detected_state,nationality,current_status,status_change_date,notes
4501,4502,NaN,06-04-2020,19.0,F,Pandalam,Pathanamthitta,Kerala,NaN,Hospitalized,06-04-2020,"Student, Travelled from Delhi in Mangala Laksh..."
6281,6282,NaN,09-04-2020,19.0,M,NaN,Kasaragod,Kerala,India,Hospitalized,09-04-2020,Contact transmission. son of another confimed ...

In [79]:

filtered_df = df[
    (df['age'] == 18) &
    (df['detected_state'].str.lower() == 'karnataka')
]

filtered_df

,id,government_id,diagnosed_date,age,gender,detected_city,detected_district,detected_state,nationality,current_status,status_change_date,notes
857,857,KA-P63,27-03-2020,18.0,M,Davangere,Davanagere,Karnataka,India,Recovered,27-03-2020,"Travel history to Paris, France"
916,916,KA-P73,28-03-2020,18.0,M,Gauribidanur,Other State,Karnataka,India,Recovered,12-04-2020,Contact of KA-P19
9258,9259,KA-P239,13-04-2020,18.0,M,Malavalli,Mandya,Karnataka,India,Hospitalized,13-04-2020,Contact of KA-P179
13638,13639,KA-P328,17-04-2020,18.0,M,NaN,Bidar,Karnataka,NaN,Hospitalized,17-04-2020,Contact with Person who travelled to Delhi
18846,18847,KA-P410,21-04-2020,18.0,F,NaN,Vijayapura,Karnataka,India,Hospitalized,21-04-2020,Contact of KA-P306
18851,18852,KA-P415,21-04-2020,18.0,F,NaN,Vijayapura,Karnataka,India,Hospitalized,21-04-2020,Contact of KA-P306
24663,24664,KA-P488,25-04-2020,18.0,M,NaN,Chikkaballapura,Karnataka,NaN,Hospitalized,25-04-2020,Travelled from Hindupur and Ananthapur